<a href="https://colab.research.google.com/github/RBCynatGlobal/1.3M_Korea/blob/main/1_3M_Korea.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import files
import re
import logging
import numpy as np
from scipy import stats
from datetime import datetime

# Configure logging
logging.basicConfig(filename='cleaning_log.txt', level=logging.INFO)

# Load the CSV file into a DataFrame (assuming the file is called 'data.csv')
# Corrected the encoding to 'utf-8-sig'
df = pd.read_csv('/content/1.3M-Korea-ggumim.co.kr-Decorating-the-House-UsersDB-csv-2020.csv', encoding='utf-8-sig')


# Preview the DataFrame
df.head(7)


# Strip whitespace from headers
df.columns = df.columns.str.strip()

# Clean up column headers by replacing spaces with underscores
df.columns = df.columns.str.replace(' ', '_')
print("Updated column names:", df.columns)

# Check for missing values and data types
print(df.info())

# Check for duplicates
print(f"Number of duplicate rows: {df.duplicated().sum()}")

# Basic statistics
df.describe(include='all')

<ipython-input-6-bc48b55ae212>:14: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/1.3M-Korea-ggumim.co.kr-Decorating-the-House-UsersDB-csv-2020.csv', encoding='utf-8-sig')

Updated column names: Index(['idx', 'name', 'nickname', 'password_secure', 'email', 'phone_number',
       'kakao_token', 'facebook_token', 'naver_token', 'account_type',
       'created_date_time'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1301500 entries, 0 to 1301499
Data columns (total 11 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   idx                1301500 non-null  int64
 1   name               1092639 non-null  object
 2   nickname           1223063 non-null  object
 3   password_secure    264721 non-null   object
 4   email              1301500 non-null  object
 5   phone_number       658399 non-null   object
 6   kakao_token        554400 non-null   object
 7   facebook_token     94600 non-null    float64
 8   naver_token        389111 non-null   float64
 9   account_type       1301446 non-null  float64
 10  created_date_time  1301466 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 109.2+ MB
None
Number of duplicate rows: 0

,idx,name,nickname,password_secure,email,phone_number,kakao_token,facebook_token,naver_token,account_type,created_date_time
count,1.301500e+06,1092639,1223063,264721,1301500,658399,554400.0,9.460000e+04,3.891110e+05,1.301446e+06,1301466
unique,NaN,326605,1220753,193287,1301500,643148,549720.0,NaN,NaN,NaN,1286635
top,NaN,.,집꾸미기,*9961083CBC24D1F2F66E7823BF8EFF91D0B1A4B6,support@ggumim.co.kr,01000000000,0.0,NaN,NaN,NaN,2020-03-19 08:15:52
freq,NaN,3334,9,61546,1,99,4008.0,NaN,NaN,NaN,6
mean,1.313451e+06,NaN,NaN,NaN,NaN,NaN,NaN,1.754424e+15,1.659314e+09,1.788565e+09,NaN
std,5.765707e+05,NaN,NaN,NaN,NaN,NaN,NaN,1.700297e+15,1.004288e+12,2.040410e+12,NaN
min,1.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,1.000000e+00,NaN
25%,8.979348e+05,NaN,NaN,NaN,NaN,NaN,NaN,8.975884e+14,2.171747e+07,1.000000e+00,NaN
50%,1.304906e+06,NaN,NaN,NaN,NaN,NaN,NaN,1.643386e+15,4.136191e+07,4.000000e+00,NaN
75%,1.769411e+06,NaN,NaN,NaN,NaN,NaN,NaN,2.135624e+15,6.690845e+07,5.000000e+00,NaN
max,2.325554e+06,NaN,NaN,NaN,NaN,NaN,NaN,1.022293e+16,6.264624e+14,2.327719e+15,NaN

WARNING: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:


# Load the CSV file into a DataFrame (assuming the file is called 'data.csv')
# Corrected the encoding to 'utf-8-sig'
df = pd.read_csv('/content/1.3M-Korea-ggumim.co.kr-Decorating-the-House-UsersDB-csv-2020.csv', encoding='utf-8-sig')


# Preview the DataFrame
df.head(7)

<ipython-input-8-31b16f9ff06b>:3: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/1.3M-Korea-ggumim.co.kr-Decorating-the-House-UsersDB-csv-2020.csv', encoding='utf-8-sig')

,idx,name,nickname,password_secure,email,phone_number,kakao_token,facebook_token,naver_token,account_type,created_date_time
0,1,집꾸미기,집꾸미기,*1FADD9336E1B9D24136E42EB1D2D5F9D86F6AA52,support@ggumim.co.kr,NaN,NaN,NaN,NaN,4.0,2014-12-05 06:42:04
1,2,클레어,NaN,NaN,ndysjo@gmail.com,NaN,NaN,NaN,NaN,3.0,2014-12-05 06:42:20
2,3,김기준,크크뤠뤠뤠,*84AAC12F54AB666ECFC2A83C676908C8BBC381B1,cray0114@gmail.com,01048600114,NaN,NaN,NaN,4.0,2014-12-05 06:46:53
3,5,admin,빵글맘42,*9961083CBC24D1F2F66E7823BF8EFF91D0B1A4B6,skdl42@naver.com,NaN,NaN,NaN,NaN,4.0,2014-12-05 06:49:46
4,6,집꾸미기,NaN,*9961083CBC24D1F2F66E7823BF8EFF91D0B1A4B6,mydearnest@osquarecorp.com,NaN,NaN,NaN,NaN,4.0,2014-12-05 06:56:17
5,8,강영덕,주화준호짱,NaN,yd8633@naver.com,010-5040-3418,NaN,7.639157e+14,NaN,2.0,2014-12-05 07:09:28
6,9,Dae Young Noh,NaN,NaN,ndysjo@hotmail.com,NaN,NaN,7.659260e+14,NaN,2.0,2014-12-05 07:29:15

In [1]:
import pandas as pd
from google.colab import files

# Step 1: Upload the file in Colab


# Load the dataset
try:
    df = pd.read_csv('/content/1.3M-Korea-ggumim.co.kr-Decorating-the-House-UsersDB-csv-2020.csv', encoding='utf-8-sig')
    print("Dataset loaded successfully.")
except Exception as e:
    print(f'Error loading dataset: {e}')
    raise

# Step 2: Validate email addresses
# Define a regex pattern for email validation
email_pattern = r'^[\w\.-]+@[\w\.-]+\.\w+$'

# Create a mask for valid emails
valid_email_mask = df['email'].str.match(email_pattern, na=False)

# Step 3: Convert `created_date_time` to proper datetime format (if present)
if 'created_date_time' in df.columns:
    df['created_date_time'] = pd.to_datetime(df['created_date_time'], errors='coerce')
    print("Converted 'created_date_time' to datetime format.")
    # Mark rows where the conversion failed as junk
    invalid_date_mask = df['created_date_time'].isna()
else:
    invalid_date_mask = pd.Series([False] * len(df))  # No invalid dates if column doesn't exist

# Step 4: Identify duplicate rows
duplicate_mask = df.duplicated()

# Step 5: Separate valid and junk datasets
valid_mask = valid_email_mask & ~invalid_date_mask & ~duplicate_mask
cleaned_df = df[valid_mask].copy()
junk_df = df[~valid_mask].copy()

print(f"Number of valid rows: {len(cleaned_df)}")
print(f"Number of junk rows: {len(junk_df)} (includes invalid emails, bad dates, and duplicates)")

# Step 6: Save the cleaned and junk datasets
cleaned_filename = 'cleaned_dataset.csv'
junk_filename = 'junk_dataset.csv'

try:
    cleaned_df.to_csv(cleaned_filename, index=False)
    junk_df.to_csv(junk_filename, index=False)
    print(f"Cleaned dataset saved to '{cleaned_filename}'.")
    print(f"Junk dataset saved to '{junk_filename}'.")
    # Automatically download the files

except Exception as e:
    print(f"Error saving datasets: {e}")
    raise

<ipython-input-1-163914bda504>:9: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/1.3M-Korea-ggumim.co.kr-Decorating-the-House-UsersDB-csv-2020.csv', encoding='utf-8-sig')

Dataset loaded successfully.
Converted 'created_date_time' to datetime format.
Number of valid rows: 1296707
Number of junk rows: 4793 (includes invalid emails, bad dates, and duplicates)
Cleaned dataset saved to 'cleaned_dataset.csv'.
Junk dataset saved to 'junk_dataset.csv'.

In [4]:
df = pd.read_csv('/content/cleaned_dataset.csv', encoding='utf-8-sig')
print(df.head(20))
print(df.tail(10))

    idx           name nickname                            password_secure  \
0     1           집꾸미기     집꾸미기  *1FADD9336E1B9D24136E42EB1D2D5F9D86F6AA52
1     2            클레어      NaN                                        NaN
2     3            김기준    크크뤠뤠뤠  *84AAC12F54AB666ECFC2A83C676908C8BBC381B1
3     5          admin    빵글맘42  *9961083CBC24D1F2F66E7823BF8EFF91D0B1A4B6
4     6           집꾸미기      NaN  *9961083CBC24D1F2F66E7823BF8EFF91D0B1A4B6
5     8            강영덕    주화준호짱                                        NaN
6     9  Dae Young Noh      NaN                                        NaN
7    10            오현균    ohwow                                        NaN
8    11            정지훈      NaN  *9961083CBC24D1F2F66E7823BF8EFF91D0B1A4B6
9    12             삐노      NaN                                        NaN
10   13            하상현      NaN                                        NaN
11   14            정현욱     우기뇽이                                        NaN
12   16            김하나      NaN  *9961083CBC24D1F2F66E7823BF8EFF91D0B1A4B6
13   17     Jihyun Ryu      NaN                                        NaN
14   18             Rz     루우루우  *E9D057131C22A0D76B4AAD2C61655BDFA706E637
15   21            하정훈      NaN  *9961083CBC24D1F2F66E7823BF8EFF91D0B1A4B6
16   27            박서영      NaN  *9961083CBC24D1F2F66E7823BF8EFF91D0B1A4B6
17   28            김정은      mks  *9961083CBC24D1F2F66E7823BF8EFF91D0B1A4B6
18   30       skullacy      NaN                                        NaN
19   33           adsf      NaN  *9961083CBC24D1F2F66E7823BF8EFF91D0B1A4B6

                         email   phone_number  kakao_token  facebook_token  \
0         support@ggumim.co.kr            NaN          NaN             NaN
1             ndysjo@gmail.com            NaN          NaN             NaN
2           cray0114@gmail.com    01048600114          NaN             NaN
3             skdl42@naver.com            NaN          NaN             NaN
4   mydearnest@osquarecorp.com            NaN          NaN             NaN
5             yd8633@naver.com  010-5040-3418          NaN    7.639157e+14
6           ndysjo@hotmail.com            NaN          NaN    7.659260e+14
7            ohsbsbs@naver.com  010-8662-5985    7781597.0             NaN
8         browniz421@gmail.com            NaN          NaN             NaN
9                    qq@qq.com            NaN          NaN             NaN
10           hsh7097@naver.com            NaN          NaN    3.911802e+14
11           mandufn@naver.com    01099802115     829933.0             NaN
12           hn10943@naver.com            NaN          NaN             NaN
13           flavaryu@nate.com            NaN          NaN    1.020547e+16
14                qq@naver.com            NaN     644986.0             NaN
15            jhha87@gmail.com            NaN          NaN             NaN
16           jen0107@naver.com            NaN          NaN             NaN
17       jung_eun115@naver.com            NaN          NaN             NaN
18          lbh880214@nate.com            NaN          NaN    2.557275e+14
19               asdf@asdf.com            NaN          NaN             NaN

    naver_token  account_type    created_date_time
0           NaN           4.0  2014-12-05 06:42:04
1           NaN           3.0  2014-12-05 06:42:20
2           NaN           4.0  2014-12-05 06:46:53
3           NaN           4.0  2014-12-05 06:49:46
4           NaN           4.0  2014-12-05 06:56:17
5           NaN           2.0  2014-12-05 07:09:28
6           NaN           2.0  2014-12-05 07:29:15
7           NaN           1.0  2014-12-05 07:51:57
8           NaN           4.0  2014-12-05 08:29:26
9           NaN           3.0  2014-12-05 08:29:41
10          NaN           2.0  2014-12-05 08:32:54
11          NaN           1.0  2014-12-05 08:39:15
12          NaN           4.0  2014-12-05 08:45:18
13          NaN           2.0  2014-12-05 08:52:08
14          NaN           1.0  2014-12-05 08:52:55
15          NaN           4.0  2014-12-05 09:09:05
16          NaN           4.0  2014-12-05 09:37:40
17          NaN           4.0  2014-12-05 09:39:14
18          NaN           2.0  2014-12-05 10:11:25
19          NaN           4.0  2014-12-05 10:17:28
             idx name    nickname password_secure                       email  \
1296697  2325544  김준엽       엽기적인나             NaN     rlawnsduq9098@naver.com
1296698  2325545  NaN    chaewonn             NaN  shimchaewoneda00@naver.com
1296699  2325546  NaN       이진이로망             NaN           05dlwls@naver.com
1296700  2325547  홍아영      꾸릅9292             NaN         ayong0902@naver.com
1296701  2325548  NaN        앤셜리헤             NaN          56231222@naver.com
1296702  2325549  유재원        재원소스             NaN        jaewon2861@naver.com
1296703  2325550  송수현  kkkongarch             NaN          dlqmsl100@nate.com
1296704  2325551  NaN       해인해빈맘             NaN            tjljh9@naver.com
1296705  2325553  NaN     slivint             NaN       rlatkdrmsdl@naver.com
1296706  2325554  NaN     눈오는날이좋아             NaN      shinae0238@hanmail.net

        phone_number   kakao_token  facebook_token  naver_token  account_type  \
1296697  01084703991  1.320360e+09             NaN          NaN           1.0
1296698  01087413013           NaN             NaN  173082288.0           5.0
1296699  01055188943           NaN             NaN  151620341.0           5.0
1296700  01075501062  1.320362e+09             NaN          NaN           1.0
1296701  01056231222           NaN             NaN   46266283.0           5.0
1296702  01030042925  1.320363e+09             NaN          NaN           1.0
1296703  01025546513  1.320363e+09             NaN          NaN           1.0
1296704  01088626799           NaN             NaN   46913432.0           5.0
1296705  01050182561           NaN             NaN   75338894.0           5.0
1296706  01065260112           NaN             NaN   16985489.0           5.0

           created_date_time
1296697  2020-03-27 21:07:36
1296698  2020-03-27 21:09:03
1296699  2020-03-27 21:09:14
1296700  2020-03-27 21:10:38
1296701  2020-03-27 21:10:57
1296702  2020-03-27 21:11:34
1296703  2020-03-27 21:12:05
1296704  2020-03-27 21:13:29
1296705  2020-03-27 21:14:22
1296706  2020-03-27 21:15:00